### ISSUE TITLE
Incorrect voting power percentage

### ISSUE THREAD

**Issue by levackt** [enigmampc/big_dipper#2]
Maybe related to #1 , if a proposal is in voting period, the percentageVoted is incorrect.

<img width="570" alt="Screenshot 2020-02-21 at 20 34 18" src="https://user-images.githubusercontent.com/10286403/75061552-9f99ee80-54e9-11ea-8214-6464eb082c24.png">

**Comment by lacabra** [comment]
Fixed in 56d4aefc330e49fb55ed146bc2e491ce545e6330
